name: optica_env
runs-on: ubuntu-latest
channels:
    - conda-forge
dependencies:
    - python
    - pip
    - setuptools
    - numpy
    - matplotlib
    - jupyterlab=3.0
    - ipywidgets=7.6.5
    - ipympl
